server:
  port: 8081

spring:
  application:
    name: ${MICROSERVICE_NAME:config-server}
    namespace: ${CLOUD_NAMESPACE:unknown}
    cloud_namespace: ${CLOUD_NAMESPACE:unknown}

mongo:
  host: ${MONGO_HOST:localhost}
  port: ${MONGO_PORT:27017}
  dbName: ${MONGO_DB_NAME:config-server}
  user: ${MONGO_USER:microservice_admin}
  password: ${MONGO_PASSWORD:microservice_admin}

---
# Items that apply to ALL profiles:
eureka:
  instance:
    appname: config-server  # ==> This is a instance of ABC-SERVICE
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:9000/eureka}
#      defaultZone: http://localhost:9001/eureka
#      defaultZone: http://localhost:9002/eureka
#      defaultZone: http://localhost:9003/eureka


---
spring:
  profiles: config-server-instance2
eureka:
  instance:
    appname: config-server
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
server:
  port: 8082

---
spring:
  profiles: config-server-instance3
eureka:
  instance:
    appname: config-server
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
server:
  port: 8083

---
spring:
  profiles: config-server-instance4
eureka:
  instance:
    appname: config-server
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
server:
  port: 8084

